apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: install-git-and-clone-repo
spec:
  workspaces:
    - name: shared-data
      description: "Workspace to store the cloned repo files"
  steps:
    - name: install-git
      image: registry.redhat.io/ubi8/ubi-minimal
      script: |
        #!/bin/sh
        microdnf install -y git
        git --version
    - name: git-clone
      image: registry.redhat.io/ubi8/ubi-minimal
      script: |
        #!/bin/sh
        git clone https://github.com/alanleberknight/nodejs-rest-http /workspace/shared-data

